<?php
declare(strict_types=1);

/**
 * Generate the temporary app-catalogue page for GitHub Pages.
 * PHP runs at build time, not on the GitHub Pages web server.
 * Usage: php scripts/build-apps-maintenance.php [--check|--stdout]
 */
if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

function renderAppsMaintenancePage(): string
{
    $copy = json_decode(<<<'COPY_JSON'
{"he":{"title":"העמוד נמצא בפיתוח","kicker":"קטלוג האפליקציות","message":"אנחנו מעדכנים את קטלוג האפליקציות. נשמח לראות אתכם שוב בקרוב.","back":"חזרה לאתר","home":"לאתר הראשי","nav":"בחירת שפה","status":"בקרוב"},"en":{"title":"This page is under development","kicker":"App catalogue","message":"We are updating our app catalogue. Please check back soon.","back":"Back to our website","home":"Main website","nav":"Choose a language","status":"Coming soon"},"ru":{"title":"Страница находится в разработке","kicker":"Каталог приложений","message":"Мы обновляем каталог приложений. Пожалуйста, зайдите позже.","back":"Вернуться на сайт","home":"Главный сайт","nav":"Выбрать язык","status":"Скоро"}}
COPY_JSON, true, 512, JSON_THROW_ON_ERROR);

    $template = <<<'PAGE_HTML'
<!doctype html>
<!-- Generated by scripts/build-apps-maintenance.php. Do not edit this file by hand. -->
<html lang="he" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex, follow">
  <meta name="theme-color" content="#10191f">
  <meta name="description" content="__DESCRIPTION__">
  <title>__TITLE__ | Edelstein Digital Lab</title>
  <link rel="canonical" href="https://9881988-lgtm.github.io/tiberias-plumbing/structo-robotics/apps.html">
  <style>
    :root { color-scheme: light; --ink: #10191f; --muted: #59676c; --paper: #f4f5f1; --accent: #c7f15b; }
    * { box-sizing: border-box; }
    body { margin: 0; min-height: 100vh; min-height: 100svh; background: var(--paper); color: var(--ink); font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif; }
    a { color: inherit; }
    .site-header { min-height: 82px; padding: 18px max(24px, calc((100vw - 1120px) / 2)); display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 20px; background: var(--ink); color: white; }
    .brand { display: inline-flex; align-items: center; gap: 12px; text-decoration: none; font-size: 18px; font-weight: 650; direction: ltr; }
    .brand-mark { display: grid; place-items: center; width: 36px; height: 36px; border: 1px solid #82945b; border-radius: 11px; color: var(--accent); font-size: 24px; }
    .languages { display: flex; gap: 6px; direction: ltr; }
    .languages button { border: 1px solid #53616a; border-radius: 9px; padding: 9px 12px; background: transparent; color: white; font: inherit; font-size: 14px; cursor: pointer; }
    .languages button[aria-pressed="true"] { background: var(--accent); border-color: var(--accent); color: var(--ink); }
    button:focus-visible, a:focus-visible { outline: 3px solid #00877f; outline-offset: 4px; }
    main { padding: 64px 24px 48px; }
    .notice { width: min(850px, 100%); margin: 0 auto; padding: clamp(30px, 6vw, 64px); border: 1px solid #d3dcda; border-radius: 24px; background: white; box-shadow: 0 20px 60px #10191f0b; }
    .status { display: inline-flex; align-items: center; gap: 9px; padding: 8px 13px; border: 1px solid #d5e5ad; border-radius: 99px; color: #3d5329; background: #f4f9e8; font-size: 14px; font-weight: 600; }
    .status::before { content: ""; width: 7px; height: 7px; border-radius: 50%; background: #718d3c; }
    .kicker { margin: 32px 0 12px; color: var(--muted); font-size: 15px; font-weight: 600; }
    h1 { margin: 0; max-width: 720px; font-size: clamp(32px, 4.8vw, 52px); line-height: 1.15; letter-spacing: -0.025em; font-weight: 700; text-wrap: balance; }
    .message { margin: 22px 0 32px; max-width: 600px; color: var(--muted); font-size: 19px; line-height: 1.65; }
    .back-link { display: inline-flex; padding: 14px 22px; border-radius: 11px; background: var(--ink); color: white; text-decoration: none; font-weight: 600; line-height: 1.4; }
    .back-link:hover { background: #243943; }
    footer { padding: 0 24px 28px; color: var(--muted); text-align: center; font-size: 13px; direction: ltr; }
    @media (max-width: 560px) { .site-header { padding: 16px 20px; gap: 14px; } .brand { font-size: 16px; } main { padding: 32px 16px; } .notice { border-radius: 18px; } .message { font-size: 17px; } }
  </style>
</head>
<body>
  <header class="site-header">
    <a class="brand" href="../digital-agency/?lang=he" data-home-link aria-label="__HOME__">
      <span class="brand-mark" aria-hidden="true">E</span>
      <span>Edelstein Digital Lab</span>
    </a>
    <nav class="languages" aria-label="__NAV__">
      <button type="button" data-lang="he" aria-pressed="true" lang="he">עברית</button>
      <button type="button" data-lang="en" aria-pressed="false" lang="en">English</button>
      <button type="button" data-lang="ru" aria-pressed="false" lang="ru">Русский</button>
    </nav>
  </header>
  <main>
    <section class="notice" aria-labelledby="notice-title">
      <span class="status" data-copy="status">__STATUS__</span>
      <p class="kicker" data-copy="kicker">__KICKER__</p>
      <h1 id="notice-title" data-copy="title">__TITLE__</h1>
      <p class="message" data-copy="message">__DESCRIPTION__</p>
      <a class="back-link" href="../digital-agency/?lang=he" data-home-link data-copy="back">__BACK__</a>
    </section>
  </main>
  <footer>Edelstein Digital Lab</footer>
  <script>
    (() => {
      "use strict";
      const copy = __COPY_JSON__;
      const buttons = document.querySelectorAll("[data-lang]");
      const applyLanguage = (requested, updateAddress) => {
        const language = Object.prototype.hasOwnProperty.call(copy, requested) ? requested : "he";
        const text = copy[language];
        document.documentElement.lang = language;
        document.documentElement.dir = language === "he" ? "rtl" : "ltr";
        document.title = text.title + " | Edelstein Digital Lab";
        document.querySelector('meta[name="description"]').content = text.message;
        document.querySelector(".languages").setAttribute("aria-label", text.nav);
        document.querySelector(".brand").setAttribute("aria-label", text.home);
        document.querySelectorAll("[data-copy]").forEach((element) => {
          element.textContent = text[element.dataset.copy];
        });
        document.querySelectorAll("[data-home-link]").forEach((link) => {
          link.href = "../digital-agency/?lang=" + language;
        });
        buttons.forEach((button) => {
          button.setAttribute("aria-pressed", String(button.dataset.lang === language));
        });
        if (updateAddress) {
          const url = new URL(window.location.href);
          url.searchParams.set("lang", language);
          window.history.replaceState(null, "", url);
        }
      };
      buttons.forEach((button) => {
        button.addEventListener("click", () => applyLanguage(button.dataset.lang, true));
      });
      applyLanguage(new URL(window.location.href).searchParams.get("lang"), false);
    })();
  </script>
</body>
</html>
PAGE_HTML;

    $escape = static fn(string $value): string =>
        htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');

    return strtr($template, [
        '__DESCRIPTION__' => $escape($copy['he']['message']),
        '__TITLE__' => $escape($copy['he']['title']),
        '__HOME__' => $escape($copy['he']['home']),
        '__NAV__' => $escape($copy['he']['nav']),
        '__STATUS__' => $escape($copy['he']['status']),
        '__KICKER__' => $escape($copy['he']['kicker']),
        '__BACK__' => $escape($copy['he']['back']),
        '__COPY_JSON__' => json_encode(
            $copy,
            JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
            | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT
            | JSON_THROW_ON_ERROR
        ),
    ]) . "\n";
}

function buildAppsMaintenancePage(array $arguments): int
{
    if (count($arguments) > 1 || (
        $arguments !== [] && !in_array($arguments[0], ['--check', '--stdout'], true)
    )) {
        fwrite(STDERR, "Usage: php scripts/build-apps-maintenance.php [--check|--stdout]\n");
        return 2;
    }

    $html = renderAppsMaintenancePage();
    if (($arguments[0] ?? '') === '--stdout') {
        fwrite(STDOUT, $html);
        return 0;
    }

    $target = dirname(__DIR__) . '/structo-robotics/apps.html';
    if (($arguments[0] ?? '') === '--check') {
        if (!is_file($target) || file_get_contents($target) !== $html) {
            fwrite(STDERR, "apps.html is out of date; run the PHP generator.\n");
            return 1;
        }
        fwrite(STDOUT, "apps.html matches the PHP generator.\n");
        return 0;
    }

    $directory = dirname($target);
    if (!is_dir($directory) || !is_writable($directory)) {
        throw new RuntimeException('Output directory is unavailable or not writable.');
    }
    $temporary = tempnam($directory, '.apps-maintenance-');
    if ($temporary === false) {
        throw new RuntimeException('Unable to create a temporary output file.');
    }
    try {
        if (file_put_contents($temporary, $html) !== strlen($html)) {
            throw new RuntimeException('Unable to write the complete page.');
        }
        if (!chmod($temporary, 0644) || !rename($temporary, $target)) {
            throw new RuntimeException('Unable to publish the generated page.');
        }
    } finally {
        if (is_file($temporary)) {
            unlink($temporary);
        }
    }
    fwrite(STDOUT, "Generated structo-robotics/apps.html with PHP.\n");
    return 0;
}

try {
    exit(buildAppsMaintenancePage(array_slice($argv, 1)));
} catch (Throwable $error) {
    fwrite(STDERR, 'Build failed: ' . $error->getMessage() . "\n");
    exit(1);
}
